### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by waynegan** [Raysmond/expper#3]
i can not login after clicking activate link from my Email in the www.expper.com,there must be some errors happening.Do you link that to the database?

**Comment by Raysmond** [comment]
Hi, you account is activated and normally you can sign in already. If not, I suggest you change another browser such as Chrome or Firefox.

**Comment by waynegan** [comment]
Thank you to reply, i try chrome and firefox, also make sure the account has been activated and password type rightly,but it does not work. password reset idle too.

**Comment by waynegan** [comment]
I may find the reason why i can not sign in, simply because i had signed in on my website which is also use Jhipster's default Oauth configuration.It should be token conflicts .
